export type Colors =
  | "primary"
  | "primary-dark"
  | "primary-darkest"
  | "yellow"
  | "yellow-light"
  | "green"
  | "green-dark"
  | "success"
  | "success-dark"
  | "danger"
  | "danger-dark"
  | "error"
  | "error-dark"
  | "info"
  | "info-dark"
  | "white"
  | "black"
  | "grey-100"
  | "grey-200"
  | "grey-300"
  | "grey-400"
  | "grey-500"
  | "grey-600"
  | "grey-700"
  | "grey-800"
  | "grey-900";

export const colorsMap = {
  primary: "primaryColor",
  "primary-dark": "primaryDarkColor",
  "primary-darkest": "primaryDarkestColor",
  yellow: "yellowColor",
  "yellow-light": "yellowLightColor",
  green: "greenColor",
  "green-dark": "greenDarkColor",
  success: "successColor",
  "success-dark": "successDarkColor",
  danger: "dangerColor",
  "danger-dark": "dangerDarkColor",
  error: "errorColor",
  "error-dark": "errorDarkColor",
  info: "infoColor",
  "info-dark": "infoDarkColor",
  white: "whiteColor",
  black: "blackColor",
  "grey-100": "grey100Color",
  "grey-200": "grey200Color",
  "grey-300": "grey300Color",
  "grey-400": "grey400Color",
  "grey-500": "grey500Color",
  "grey-600": "grey600Color",
  "grey-700": "grey700Color",
  "grey-800": "grey800Color",
  "grey-900": "grey900Color",
};
