import { Colors } from "../src/types/colors";

export const colorVariants: Colors[] = [
  "primary",
  "primary-dark",
  "primary-darkest",
  "yellow",
  "yellow-light",
  "green",
  "green-dark",
  "success",
  "success-dark",
  "danger",
  "danger-dark",
  "error",
  "error-dark",
  "info",
  "info-dark",
  "white",
  "black",
  "grey-100",
  "grey-200",
  "grey-300",
  "grey-400",
  "grey-500",
  "grey-600",
  "grey-700",
  "grey-800",
  "grey-900",
];
