export { default as Button } from "./components/Button/Button";
export type { ButtonProps } from "./components/Button/Button.types";
export { default as Paragraph } from "./components/Paragraph/Paragraph";
export type { ParagraphProps } from "./components/Paragraph/Paragraph.types";
export { default as PromoCardType1 } from "./components/PromoCard/components/PromoCardType1/PromoCardType1";
export type { PromoCardType1Props } from "./components/PromoCard/components/PromoCardType1/PromoCardType1.types";
export { default as PromoCardType2 } from "./components/PromoCard/components/PromoCardType2/PromoCardType2";
export type { PromoCardType2Props } from "./components/PromoCard/components/PromoCardType2/PromoCardType2.types";
export { default as PromoCardType3 } from "./components/PromoCard/components/PromoCardType3/PromoCardType3";
export type { PromoCardType3Props } from "./components/PromoCard/components/PromoCardType3/PromoCardType3.types";
